### ISSUE TITLE
Redirect user back to the page they were on when they logged in

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/resources-portal#804] opened 2021-03-26 20:52 UTC
### Context

Found during eval. User signed in on resource details page

### Problem or idea

User signed in on resource details page and after signing them in, it took them to `My account` page. This should redirect them back to the page they were on since they are in the middle of a task there and taking them to `My account` is disorienting + they need to put the effort to navigate back the original page. 

### Solution or next step

We should just take them back to the page where they signed in whenever we have a CTA that says `Sign in to X`.

**Comment by davidsmejia** [comment] 2021-04-13 15:50
Create account redirect back to where they were check for after the post new user

**Comment by davidsmejia** [comment] 2021-06-03 15:33
duplicate of #831

**Closed by davidsmejia** 2021-06-03 15:33 UTC
Labels: High Priority, user feedback
